### PR TITLE
PDF / HTML / DOCX manuals from Markdown

### PR DESCRIPTION
**Pull request by class101**
Hi @ToyKeeper ,

First of all, congratulations on the amazing work you're putting into Anduril, it's truly impressive! 

I was pleasantly surprised to find a perfectly detailed Markdown documentation, and it inspired me to share a skill that I usually pass on. This time, I made sure to match the quality of your work by thoroughly documenting how I generate HTML and PDF manuals from your Markdown file.

The result is quite remarkable, in my opinion. What do you think? 

I took care to include the compiled HTML and PDF files so you can see the outcome for yourself. 

- [anduril-manual.pdf](https://github.com/class101/anduril/blob/trunk/docs/anduril-manual.pdf)
- [anduril-manual.docx](https://github.com/class101/anduril/blob/trunk/docs/anduril-manual.docx)
- [anduril-manual.html](https://github.com/class101/anduril/blob/trunk/docs/anduril-manual.html)
- [anduril-manual-2.html](https://github.com/class101/anduril/blob/trunk/docs/anduril-manual-2.html)
- [anduril-manual-build-README.md](https://github.com/class101/anduril/blob/trunk/docs/anduril-manual-build-README.md)

I'm planning to make this my EDC manual, which will stay on my phone. :D

Kudos to the team! 

Of course, if you don’t have the environment to compile the file, I’d be happy to do it for you. I'm now actively following the progress of your project! 

Best regards,  
Arnaud

### CODE REVIEW

**Comment by class101** [comment]
Note1:

Although the changes are 99% due to alignment, I have decided to add a link to an external diagram of @containerfan. This change may not suit you, so feel free to remove them if they bother you (the two diagrams are attached at the end of the documentation).

**Comment by class101** [comment]
Note2:

I don't anticipate any major changes except for continuing some improvements on alignments so that it displays perfectly in MD, PDF, HTML, and DOCX.

The MD syntax is remarkably well done from what I observe, at 99% accuracy, kudos for that Team. There are just a few minor corrections here and there to improve overall readability I believe

**Comment by SammysHP** [comment]
Build artifacts (docx, PDF, HTML) should not be included in the repository when they are just compiled from the markdown source (and if manual adjustments are required, they should be added to the build step).

**Comment by class101** [comment]
It was a favor I was doing for you because I primarily built the PDF for myself.

If you're being picky, it means you don't need it, so just stick to that finger in the ass you have and that unlinted Markdown :)

**Comment by class101** [comment]
Additionally, it's worth noting that your build process is outdated and archaic, using a Makefile. Wow. 

in its current state, it's clear that this isn't a motivating project to add a documentation build process to.

You should modernize your build cycle, for example, by using CMake, document your build process, make it OS-independent, and then, yes, it would be justified to be extremely picky as you have demonstrated

You are taking yourselves so seriously without even deploying serious tools; learn to accept what's being offered to you in the future

**Comment by SammysHP** [comment]
Uhm... Don't you think your choice of words is a little rude? I simply said that build artifacts shouldn't be committed to the repository, only the instructions to create them.

Make is a proven and still up-to-date tool for building. I don't see anything wrong with using it in a project of this size. Documenting the build process? What kind of documentation is missing in your opinion? Running "make" is basically all that is required. Setting up the build environment requires a few more steps, but that's why there is a Docker image that can be used for building. OS independent? I don't see how it should work, considering that the tools used for building don't run natively under Windows.

I'm not the owner of this repository, but considering your behavior, I'd prefer to not include your changes under these circumstances.

**Comment by ToyKeeper** [comment]
Well, that was neat.

**Comment by SiteRelEnby** [comment]
@class101 the Makefile is just a wrapper some people wanted, in order to call the actual build script which is well structured, as you would see if you actually bothered to follow the actual execution flow of the build toolchain.

Committing artifacts to the repo *is* bad practice, and just creates massive bloat in the git repo. It's the sort of thing that rendering a PDF as part of a build process is great, but people who are actually checking out the repo generally are for purposes of hacking on it.

There already is an OS independent build toolchain (which I will admit, I need to do some work on updating as right now it is poorly documented, but it's runnable as is, and IIRC I have a PR open to integrate it into the scripts to make it more easily discoverable).

**Comment by class101** [comment]
Sorry @SammysHP @SiteRelEnby I was in a bit of a bad mood the other day.

To be honest, for a project of this scope, I think a merge request is premature at the moment. I'll probably follow containerfan's example and publish the project under the repo **anduril-manual-pdf**.

For now, I'll just focus on fixing cosmetic issues, and if later it makes sense to integrate it into the build cycle, it might be wise for you to modernize the build process.

Because to me, committing a Makefile is like committing a .sln file, it's a bad practice since it's designed for a specific operating system.

If you're not familiar with it, I recommend checking out **CMake**, which, with a single **CMakeLists.txt** file, understands all OSs, all IDEs, and can compile your project the way you've defined it.

CMake is really awesome and very modern.

**Pull request closed without merging**
